# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'broches.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Broches(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 680)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(570, 90, 151, 141))
        self.label_21.setStyleSheet("image: url(:/produtos/Broches/simpsons-broce.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_21.setObjectName("label_21")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(90, 240, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(340, 90, 161, 141))
        self.label_18.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/onepiece-preto-bone.png);\n"
"image: url(:/produtos/Broches/onepiece-broche.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(340, 230, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(570, 230, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(90, 90, 181, 141))
        self.label_16.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/naruto-preto-bone.png);\n"
"image: url(:/produtos/Broches/naruto-broce.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_16.setObjectName("label_16")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 61, 61))
        self.label_6.setStyleSheet("image: url(:/icons/icones/Gamepad(1).png);\n"
"image: url(:/icons/icones/Gamepad (3).png);")
        self.label_6.setObjectName("label_6")
        self.botao_add_broche_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_broche_naruto.setGeometry(QtCore.QRect(90, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_broche_naruto.setFont(font)
        self.botao_add_broche_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_broche_naruto.setObjectName("botao_add_broche_naruto")
        self.botao_add_broche_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_broche_onep.setGeometry(QtCore.QRect(330, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_broche_onep.setFont(font)
        self.botao_add_broche_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_broche_onep.setObjectName("botao_add_broche_onep")
        self.botao_add_broche_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_broche_simpsons.setGeometry(QtCore.QRect(570, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_broche_simpsons.setFont(font)
        self.botao_add_broche_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_broche_simpsons.setObjectName("botao_add_broche_simpsons")
        self.botao_voltar = QtWidgets.QPushButton(Dialog)
        self.botao_voltar.setGeometry(QtCore.QRect(10, 640, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_voltar.setObjectName("botao_voltar")
        self.botao_carrinho = QtWidgets.QPushButton(Dialog)
        self.botao_carrinho.setGeometry(QtCore.QRect(730, 10, 51, 51))
        self.botao_carrinho.setStyleSheet("image: url(:/icons/icones/carr.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:black;")
        self.botao_carrinho.setText("")
        self.botao_carrinho.setObjectName("botao_carrinho")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(350, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.botao_add_caneca_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_caneca_onep.setGeometry(QtCore.QRect(330, 570, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_caneca_onep.setFont(font)
        self.botao_add_caneca_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_caneca_onep.setObjectName("botao_add_caneca_onep")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(90, 520, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(570, 370, 151, 141))
        self.label_23.setStyleSheet("image: url(:/produtos/shorts/caneca-simpsons.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(340, 510, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(570, 510, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(340, 370, 161, 141))
        self.label_26.setStyleSheet("image: url(:/produtos/shorts/caneca-onep.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_26.setObjectName("label_26")
        self.botao_add_caneca_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_caneca_simpsons.setGeometry(QtCore.QRect(570, 570, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_caneca_simpsons.setFont(font)
        self.botao_add_caneca_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_caneca_simpsons.setObjectName("botao_add_caneca_simpsons")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(90, 370, 181, 141))
        self.label_27.setStyleSheet("image: url(:/produtos/shorts/caneca-naruto.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_27.setObjectName("label_27")
        self.botao_add_caneca_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_caneca_naruto.setGeometry(QtCore.QRect(90, 570, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_caneca_naruto.setFont(font)
        self.botao_add_caneca_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_caneca_naruto.setObjectName("botao_add_caneca_naruto")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p>BROCHE NARUTO</p><p><span style=\" font-weight:600;\">R$ 15,00</span></p><p><br/></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p>BROCHE ONE PIECE</p><p><span style=\" font-weight:600;\">R$ 15,00</span></p></body></html>"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p>BROCHE SIMPSONS</p><p><span style=\" font-weight:600;\">R$ 15,00</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.botao_add_broche_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_add_broche_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_add_broche_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_voltar.setText(_translate("Dialog", "VOLTAR"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">ACESSÓRIOS</span></p><p><br/></p></body></html>"))
        self.botao_add_caneca_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p>CANECA NARUTO</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p><p><br/></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p>CANECA ONE PIECE</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>CANECA SIMPSONS</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p></body></html>"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_caneca_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_caneca_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
import template.imgicons
import template.produtos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Broches()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
