# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camisas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Camisas(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 670)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_add_camisa_branca_simpsonss = QtWidgets.QPushButton(Dialog)
        self.botao_add_camisa_branca_simpsonss.setGeometry(QtCore.QRect(570, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_camisa_branca_simpsonss.setFont(font)
        self.botao_add_camisa_branca_simpsonss.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_camisa_branca_simpsonss.setObjectName("botao_add_camisa_branca_simpsonss")
        self.botao_add_camisa_preta_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_camisa_preta_onep.setGeometry(QtCore.QRect(330, 560, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_camisa_preta_onep.setFont(font)
        self.botao_add_camisa_preta_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_camisa_preta_onep.setObjectName("botao_add_camisa_preta_onep")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(90, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(340, 360, 161, 141))
        self.label_26.setStyleSheet("image: url(:/produtos/Camisas/One Piece, Naruto e Simpsons/onepiece-preta.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_26.setObjectName("label_26")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.label_6.setStyleSheet("image: url(:/icons/icones/Gamepad(1).png);\n"
"image: url(:/icons/icones/Gamepad (3).png);")
        self.label_6.setObjectName("label_6")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(90, 80, 181, 141))
        self.label_16.setStyleSheet("image: url(:/produtos/Camisas/One Piece, Naruto e Simpsons/naturo-branca.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_16.setObjectName("label_16")
        self.botao_add_camisa_branca_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_camisa_branca_onep.setGeometry(QtCore.QRect(330, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_camisa_branca_onep.setFont(font)
        self.botao_add_camisa_branca_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_camisa_branca_onep.setObjectName("botao_add_camisa_branca_onep")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(570, 80, 151, 141))
        self.label_21.setStyleSheet("image: url(:/produtos/Camisas/One Piece, Naruto e Simpsons/simpsons-branco.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_21.setObjectName("label_21")
        self.botao_add_camisa_preta_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_camisa_preta_naruto.setGeometry(QtCore.QRect(90, 560, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_camisa_preta_naruto.setFont(font)
        self.botao_add_camisa_preta_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_camisa_preta_naruto.setObjectName("botao_add_camisa_preta_naruto")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(340, 230, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.botao_voltar = QtWidgets.QPushButton(Dialog)
        self.botao_voltar.setGeometry(QtCore.QRect(10, 630, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_voltar.setObjectName("botao_voltar")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(570, 510, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(570, 360, 151, 141))
        self.label_23.setStyleSheet("image: url(:/produtos/Camisas/One Piece, Naruto e Simpsons/simpsons-preto.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_23.setObjectName("label_23")
        self.botao_add_camisa_branca_simpsons = QtWidgets.QLabel(Dialog)
        self.botao_add_camisa_branca_simpsons.setGeometry(QtCore.QRect(570, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.botao_add_camisa_branca_simpsons.setFont(font)
        self.botao_add_camisa_branca_simpsons.setObjectName("botao_add_camisa_branca_simpsons")
        self.botao_add_camisa_branca_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_camisa_branca_naruto.setGeometry(QtCore.QRect(90, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_camisa_branca_naruto.setFont(font)
        self.botao_add_camisa_branca_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_camisa_branca_naruto.setObjectName("botao_add_camisa_branca_naruto")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(340, 80, 161, 141))
        self.label_18.setStyleSheet("image: url(:/produtos/Camisas/One Piece, Naruto e Simpsons/onepiece-branca.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_18.setObjectName("label_18")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(340, 510, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.botao_carrinho = QtWidgets.QPushButton(Dialog)
        self.botao_carrinho.setGeometry(QtCore.QRect(740, 10, 51, 51))
        self.botao_carrinho.setStyleSheet("image: url(:/icons/icones/carr.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:black;")
        self.botao_carrinho.setText("")
        self.botao_carrinho.setObjectName("botao_carrinho")
        self.botao_add_camisa_preta_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_camisa_preta_simpsons.setGeometry(QtCore.QRect(570, 560, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_camisa_preta_simpsons.setFont(font)
        self.botao_add_camisa_preta_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_camisa_preta_simpsons.setObjectName("botao_add_camisa_preta_simpsons")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(90, 510, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(90, 360, 181, 141))
        self.label_27.setStyleSheet("image: url(:/produtos/Camisas/One Piece, Naruto e Simpsons/naturo-preta.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_27.setObjectName("label_27")
        self.tamanho_camisa_branca_simpsons = QtWidgets.QComboBox(Dialog)
        self.tamanho_camisa_branca_simpsons.setGeometry(QtCore.QRect(700, 250, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_camisa_branca_simpsons.setFont(font)
        self.tamanho_camisa_branca_simpsons.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_camisa_branca_simpsons.setObjectName("tamanho_camisa_branca_simpsons")
        self.tamanho_camisa_branca_simpsons.addItem("")
        self.tamanho_camisa_branca_simpsons.addItem("")
        self.tamanho_camisa_branca_simpsons.addItem("")
        self.tamanho_camisa_preto_simpsons = QtWidgets.QComboBox(Dialog)
        self.tamanho_camisa_preto_simpsons.setGeometry(QtCore.QRect(700, 530, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_camisa_preto_simpsons.setFont(font)
        self.tamanho_camisa_preto_simpsons.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_camisa_preto_simpsons.setObjectName("tamanho_camisa_preto_simpsons")
        self.tamanho_camisa_preto_simpsons.addItem("")
        self.tamanho_camisa_preto_simpsons.addItem("")
        self.tamanho_camisa_preto_simpsons.addItem("")
        self.tamanho_camisa_branca_onepiece = QtWidgets.QComboBox(Dialog)
        self.tamanho_camisa_branca_onepiece.setGeometry(QtCore.QRect(470, 250, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_camisa_branca_onepiece.setFont(font)
        self.tamanho_camisa_branca_onepiece.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_camisa_branca_onepiece.setObjectName("tamanho_camisa_branca_onepiece")
        self.tamanho_camisa_branca_onepiece.addItem("")
        self.tamanho_camisa_branca_onepiece.addItem("")
        self.tamanho_camisa_branca_onepiece.addItem("")
        self.tamanho_camisa_preto_onepiece = QtWidgets.QComboBox(Dialog)
        self.tamanho_camisa_preto_onepiece.setGeometry(QtCore.QRect(470, 530, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_camisa_preto_onepiece.setFont(font)
        self.tamanho_camisa_preto_onepiece.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_camisa_preto_onepiece.setObjectName("tamanho_camisa_preto_onepiece")
        self.tamanho_camisa_preto_onepiece.addItem("")
        self.tamanho_camisa_preto_onepiece.addItem("")
        self.tamanho_camisa_preto_onepiece.addItem("")
        self.tamanho_camisa_branca_naruto = QtWidgets.QComboBox(Dialog)
        self.tamanho_camisa_branca_naruto.setGeometry(QtCore.QRect(210, 250, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_camisa_branca_naruto.setFont(font)
        self.tamanho_camisa_branca_naruto.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_camisa_branca_naruto.setObjectName("tamanho_camisa_branca_naruto")
        self.tamanho_camisa_branca_naruto.addItem("")
        self.tamanho_camisa_branca_naruto.addItem("")
        self.tamanho_camisa_branca_naruto.addItem("")
        self.tamanho_camisa_preto_naruto = QtWidgets.QComboBox(Dialog)
        self.tamanho_camisa_preto_naruto.setGeometry(QtCore.QRect(210, 530, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_camisa_preto_naruto.setFont(font)
        self.tamanho_camisa_preto_naruto.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_camisa_preto_naruto.setObjectName("tamanho_camisa_preto_naruto")
        self.tamanho_camisa_preto_naruto.addItem("")
        self.tamanho_camisa_preto_naruto.addItem("")
        self.tamanho_camisa_preto_naruto.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.botao_add_camisa_branca_simpsonss.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_add_camisa_preta_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p>CAMISA NARUTO - BRANCA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">CAMISAS</span></p></body></html>"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_camisa_branca_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_camisa_preta_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p>CAMISA ONE PIECE - BRANCA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.botao_voltar.setText(_translate("Dialog", "VOLTAR"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>CAMISA SIMPSONS - PRETA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_camisa_branca_simpsons.setText(_translate("Dialog", "<html><head/><body><p>CAMISA SIMPSONS - BRANCA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.botao_add_camisa_branca_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p>CAMISA ONE PIECE - PRETA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.botao_add_camisa_preta_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p>CAMISA NARUTO - PRETA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.tamanho_camisa_branca_simpsons.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_camisa_branca_simpsons.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_camisa_branca_simpsons.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_camisa_preto_simpsons.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_camisa_preto_simpsons.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_camisa_preto_simpsons.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_camisa_branca_onepiece.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_camisa_branca_onepiece.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_camisa_branca_onepiece.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_camisa_preto_onepiece.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_camisa_preto_onepiece.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_camisa_preto_onepiece.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_camisa_branca_naruto.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_camisa_branca_naruto.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_camisa_branca_naruto.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_camisa_preto_naruto.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_camisa_preto_naruto.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_camisa_preto_naruto.setItemText(2, _translate("Dialog", "G"))
import template.imgicons
import template.produtos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Camisas()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
