# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caralho.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import produtos
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carrinho(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 670)
        Dialog.setFixedSize(800, 670)

        self.label_titulo = QtWidgets.QLabel(Dialog)
        self.label_titulo.setGeometry(QtCore.QRect(338, 30, 123, 41))
        self.label_titulo.setText("CARRINHO")

        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(20)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label")

        self.label_subtotal = QtWidgets.QLabel(Dialog)
        self.label_subtotal.setGeometry(QtCore.QRect(610, 580, 47, 13))
        self.label_subtotal.setObjectName("label_subtotal")
        self.label_subtotal.setText(f"Subtotal: ")
        self.label_subtotal.adjustSize()

        self.label_total = QtWidgets.QLabel(Dialog)
        self.label_total.setGeometry(QtCore.QRect(610, 600, 47, 13))
        self.label_total.setObjectName("label_total")
        self.label_total.setText(f"Total: ")
        self.label_total.adjustSize()

        self.button_voltar = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_voltar.setFont(font)
        self.button_voltar.setStyleSheet("QPushButton {\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(0, 0, 0);\n"
                                         "border-style:outset;\n"
                                         "border-width: 2px;\n"
                                         "border-radius: 15px;\n"
                                         "border-color:black;\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "color:black;\n"
                                         "background-color:white;\n"
                                         "border-style:outset;\n"
                                         "border-width: 2px;\n"
                                         "border-radius: 15px;\n"
                                         "border-color:black;\n"
                                         "}")
        self.button_voltar.setGeometry(QtCore.QRect(60, 630, 75, 23))
        self.button_voltar.setObjectName("pushButton")

        self.button_finalizar = QtWidgets.QPushButton(Dialog)
        self.button_finalizar.setGeometry(QtCore.QRect(650, 640, 75, 23))
        self.button_finalizar.setObjectName("pushButton_2")

        self.scroll = QtWidgets.QScrollArea(Dialog)
        self.widgetScroll = QtWidgets.QWidget()
        self.vBox = QtWidgets.QVBoxLayout()

        self.widgetScroll.setLayout(self.vBox)

        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widgetScroll.sizePolicy().hasHeightForWidth())

        self.widgetScroll.setSizePolicy(sizePolicy)

        self.scroll.setWidget(self.widgetScroll)

        self.scroll.setGeometry(QtCore.QRect(60, 100, 680, 450))
        self.scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll.setWidgetResizable(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle("Dialog")
        self.button_voltar.setText(_translate("Dialog", "Voltar"))
        self.button_finalizar.setText(_translate("Dialog", "Finalizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Carrinho()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
