# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chapeus.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chapeus(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 680)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(310, 530, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(310, 360, 201, 161))
        self.label_24.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/onepiece-branco-bone.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_24.setObjectName("label_24")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(540, 70, 191, 161))
        self.label_21.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_21.setObjectName("label_21")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(90, 530, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(90, 70, 191, 161))
        self.label_16.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/naruto-preto-bone.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_16.setObjectName("label_16")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(90, 360, 191, 161))
        self.label_22.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/naruto-branco-bone.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_22.setObjectName("label_22")
        self.botao_add_chapeu_branco_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_chapeu_branco_simpsons.setGeometry(QtCore.QRect(560, 580, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_chapeu_branco_simpsons.setFont(font)
        self.botao_add_chapeu_branco_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_chapeu_branco_simpsons.setObjectName("botao_add_chapeu_branco_simpsons")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(540, 530, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(360, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(310, 70, 201, 161))
        self.label_18.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/onepiece-preto-bone.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_18.setObjectName("label_18")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(540, 360, 191, 161))
        self.label_23.setStyleSheet("image: url(:/produtos/bones/One piece, Naruto, Simpsons/simpsons-branco-bone.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_23.setObjectName("label_23")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.label_6.setStyleSheet("image: url(:/icons/icones/Gamepad(1).png);\n"
"image: url(:/icons/icones/Gamepad (3).png);")
        self.label_6.setObjectName("label_6")
        self.botao_add_chapeu_branco_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_chapeu_branco_naruto.setGeometry(QtCore.QRect(110, 580, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_chapeu_branco_naruto.setFont(font)
        self.botao_add_chapeu_branco_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_chapeu_branco_naruto.setObjectName("botao_add_chapeu_branco_naruto")
        self.botao_add_chapeu_branco_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_chapeu_branco_onep.setGeometry(QtCore.QRect(320, 580, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_chapeu_branco_onep.setFont(font)
        self.botao_add_chapeu_branco_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_chapeu_branco_onep.setObjectName("botao_add_chapeu_branco_onep")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(310, 240, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.botao_add_chapeu_preto_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_chapeu_preto_onep.setGeometry(QtCore.QRect(320, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        font.setUnderline(False)
        self.botao_add_chapeu_preto_onep.setFont(font)
        self.botao_add_chapeu_preto_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_chapeu_preto_onep.setObjectName("botao_add_chapeu_preto_onep")
        self.botao_add_chapeu_preto_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_chapeu_preto_simpsons.setGeometry(QtCore.QRect(560, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_chapeu_preto_simpsons.setFont(font)
        self.botao_add_chapeu_preto_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_chapeu_preto_simpsons.setObjectName("botao_add_chapeu_preto_simpsons")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(540, 240, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.botao_add_chapeu_preto_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_chapeu_preto_naruto.setGeometry(QtCore.QRect(110, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_chapeu_preto_naruto.setFont(font)
        self.botao_add_chapeu_preto_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_chapeu_preto_naruto.setObjectName("botao_add_chapeu_preto_naruto")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(90, 240, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.botao_voltar = QtWidgets.QPushButton(Dialog)
        self.botao_voltar.setGeometry(QtCore.QRect(10, 630, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_voltar.setObjectName("botao_voltar")
        self.botao_carrinho = QtWidgets.QPushButton(Dialog)
        self.botao_carrinho.setGeometry(QtCore.QRect(730, 10, 51, 51))
        self.botao_carrinho.setStyleSheet("image: url(:/icons/icones/carr.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:black;")
        self.botao_carrinho.setText("")
        self.botao_carrinho.setObjectName("botao_carrinho")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p>CHAPÉU UNISSEX ONE PIECE - BRANCO</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p><p><br/></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p>CHAPÉU UNISSEX NARUTO - BRANCO</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p><p><br/></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_chapeu_branco_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>CHAPÉU UNISSEX SIMPSONS - BRANCO</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">CHAPÉUS</span></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.botao_add_chapeu_branco_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_add_chapeu_branco_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p>CHAPÉU UNISSEX ONE PIECE - BRANCO</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p><p><br/></p></body></html>"))
        self.botao_add_chapeu_preto_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_add_chapeu_preto_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p>CHAPÉU UNISSEX SIMPSONS - BRANCO</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p><p><br/></p></body></html>"))
        self.botao_add_chapeu_preto_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p>CHAPÉU UNISSEX NARUTO - BRANCO</p><p><span style=\" font-weight:600;\">R$ 30,00</span></p><p><br/></p></body></html>"))
        self.botao_voltar.setText(_translate("Dialog", "VOLTAR"))

import template.imgicons
import template.produtos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Chapeus()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
