# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 300)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_usuario = QtWidgets.QLineEdit(Dialog)
        self.input_usuario.setGeometry(QtCore.QRect(80, 150, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        self.input_usuario.setFont(font)
        self.input_usuario.setObjectName("input_usuario")
        self.input_senha = QtWidgets.QLineEdit(Dialog)
        self.input_senha.setGeometry(QtCore.QRect(80, 180, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        self.input_senha.setFont(font)
        self.input_senha.setStyleSheet("")
        self.input_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha.setObjectName("input_senha")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.check_lembrar = QtWidgets.QCheckBox(Dialog)
        self.check_lembrar.setGeometry(QtCore.QRect(80, 210, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.check_lembrar.setFont(font)
        self.check_lembrar.setObjectName("check_lembrar")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 151, 121))
        self.label_3.setStyleSheet("image: url(:/icons/icones/Gamepad.png);\n"
"")
        self.label_3.setObjectName("label_3")
        self.botao_cadastro = QtWidgets.QPushButton(Dialog)
        self.botao_cadastro.setGeometry(QtCore.QRect(70, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_cadastro.setFont(font)
        self.botao_cadastro.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_cadastro.setObjectName("botao_cadastro")
        self.botao_login = QtWidgets.QPushButton(Dialog)
        self.botao_login.setGeometry(QtCore.QRect(160, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_login.setFont(font)
        self.botao_login.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_login.setObjectName("botao_login")
        self.botao_sair = QtWidgets.QPushButton(Dialog)
        self.botao_sair.setGeometry(QtCore.QRect(10, 260, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_sair.setFont(font)
        self.botao_sair.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_sair.setObjectName("botao_sair")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.input_usuario.setPlaceholderText(_translate("Dialog", "Digite seu usuário"))
        self.input_senha.setPlaceholderText(_translate("Dialog", "Digite sua senha"))
        self.label_4.setText(_translate("Dialog", "Usuário"))
        self.label_5.setText(_translate("Dialog", "Senha"))
        self.check_lembrar.setText(_translate("Dialog", "Lembre-se de mim"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.botao_cadastro.setText(_translate("Dialog", "Cadastre-se"))
        self.botao_login.setText(_translate("Dialog", "Login"))
        self.botao_sair.setText(_translate("Dialog", "Sair"))

import template.imgicons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
