# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moletom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Moletons(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 680)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(80, 220, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(330, 350, 161, 141))
        self.label_26.setStyleSheet("image: url(:/produtos/Moletons/One piece, Naruto e Simpsons/onepiece-preto-moletom.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_26.setObjectName("label_26")
        self.botao_carrinho = QtWidgets.QPushButton(Dialog)
        self.botao_carrinho.setGeometry(QtCore.QRect(730, 10, 51, 51))
        self.botao_carrinho.setStyleSheet("image: url(:/icons/icones/carr.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:black;")
        self.botao_carrinho.setText("")
        self.botao_carrinho.setObjectName("botao_carrinho")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(560, 500, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(560, 220, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.label_6.setStyleSheet("image: url(:/icons/icones/Gamepad(1).png);\n"
"image: url(:/icons/icones/Gamepad (3).png);")
        self.label_6.setObjectName("label_6")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(80, 500, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(330, 220, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.botao_add_moletom_preto_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_moletom_preto_naruto.setGeometry(QtCore.QRect(80, 550, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_moletom_preto_naruto.setFont(font)
        self.botao_add_moletom_preto_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_moletom_preto_naruto.setObjectName("botao_add_moletom_preto_naruto")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(560, 350, 151, 141))
        self.label_23.setStyleSheet("image: url(:/produtos/Moletons/One piece, Naruto e Simpsons/simpsons-preto-moletom.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_23.setObjectName("label_23")
        self.botao_add_moletom_branco_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_moletom_branco_onep.setGeometry(QtCore.QRect(320, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_moletom_branco_onep.setFont(font)
        self.botao_add_moletom_branco_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_moletom_branco_onep.setObjectName("botao_add_moletom_branco_onep")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(360, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(330, 70, 161, 141))
        self.label_18.setStyleSheet("image: url(:/produtos/Moletons/One piece, Naruto e Simpsons/onepiece-branco-moletom.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(560, 70, 151, 141))
        self.label_21.setStyleSheet("image: url(:/produtos/Moletons/One piece, Naruto e Simpsons/simpsons-branco-moletom.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_21.setObjectName("label_21")
        self.botao_add_moletom_preto_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_moletom_preto_onep.setGeometry(QtCore.QRect(320, 550, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_moletom_preto_onep.setFont(font)
        self.botao_add_moletom_preto_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_moletom_preto_onep.setObjectName("botao_add_moletom_preto_onep")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(80, 70, 181, 141))
        self.label_16.setStyleSheet("image: url(:/produtos/Moletons/One piece, Naruto e Simpsons/naturo-branco-moletom.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_16.setObjectName("label_16")
        self.botao_add_moletom_branco_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_moletom_branco_naruto.setGeometry(QtCore.QRect(80, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_moletom_branco_naruto.setFont(font)
        self.botao_add_moletom_branco_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_moletom_branco_naruto.setObjectName("botao_add_moletom_branco_naruto")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(330, 500, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.botao_add_moletom_preto_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_moletom_preto_simpsons.setGeometry(QtCore.QRect(560, 550, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_moletom_preto_simpsons.setFont(font)
        self.botao_add_moletom_preto_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_moletom_preto_simpsons.setObjectName("botao_add_moletom_preto_simpsons")
        self.botao_add_moletom_branco_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_moletom_branco_simpsons.setGeometry(QtCore.QRect(560, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_moletom_branco_simpsons.setFont(font)
        self.botao_add_moletom_branco_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_moletom_branco_simpsons.setObjectName("botao_add_moletom_branco_simpsons")
        self.botao_voltar = QtWidgets.QPushButton(Dialog)
        self.botao_voltar.setGeometry(QtCore.QRect(10, 640, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_voltar.setObjectName("botao_voltar")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(80, 350, 181, 141))
        self.label_27.setStyleSheet("image: url(:/produtos/Moletons/One piece, Naruto e Simpsons/naturo-preta-moletom.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_27.setObjectName("label_27")
        self.tamanho_moletom_preto_simpsons = QtWidgets.QComboBox(Dialog)
        self.tamanho_moletom_preto_simpsons.setGeometry(QtCore.QRect(700, 520, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_moletom_preto_simpsons.setFont(font)
        self.tamanho_moletom_preto_simpsons.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_moletom_preto_simpsons.setObjectName("tamanho_moletom_preto_simpsons")
        self.tamanho_moletom_preto_simpsons.addItem("")
        self.tamanho_moletom_preto_simpsons.addItem("")
        self.tamanho_moletom_preto_simpsons.addItem("")
        self.tamanho_moletom_branco_onepiece = QtWidgets.QComboBox(Dialog)
        self.tamanho_moletom_branco_onepiece.setGeometry(QtCore.QRect(470, 240, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_moletom_branco_onepiece.setFont(font)
        self.tamanho_moletom_branco_onepiece.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_moletom_branco_onepiece.setObjectName("tamanho_moletom_branco_onepiece")
        self.tamanho_moletom_branco_onepiece.addItem("")
        self.tamanho_moletom_branco_onepiece.addItem("")
        self.tamanho_moletom_branco_onepiece.addItem("")
        self.tamanho_moletom_branco_naruto = QtWidgets.QComboBox(Dialog)
        self.tamanho_moletom_branco_naruto.setGeometry(QtCore.QRect(210, 240, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_moletom_branco_naruto.setFont(font)
        self.tamanho_moletom_branco_naruto.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_moletom_branco_naruto.setObjectName("tamanho_moletom_branco_naruto")
        self.tamanho_moletom_branco_naruto.addItem("")
        self.tamanho_moletom_branco_naruto.addItem("")
        self.tamanho_moletom_branco_naruto.addItem("")
        self.tamanho_moletom_preto_onepiece = QtWidgets.QComboBox(Dialog)
        self.tamanho_moletom_preto_onepiece.setGeometry(QtCore.QRect(470, 520, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_moletom_preto_onepiece.setFont(font)
        self.tamanho_moletom_preto_onepiece.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_moletom_preto_onepiece.setObjectName("tamanho_moletom_preto_onepiece")
        self.tamanho_moletom_preto_onepiece.addItem("")
        self.tamanho_moletom_preto_onepiece.addItem("")
        self.tamanho_moletom_preto_onepiece.addItem("")
        self.tamanho_moletom_branco_simpsons = QtWidgets.QComboBox(Dialog)
        self.tamanho_moletom_branco_simpsons.setGeometry(QtCore.QRect(700, 240, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_moletom_branco_simpsons.setFont(font)
        self.tamanho_moletom_branco_simpsons.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_moletom_branco_simpsons.setObjectName("tamanho_moletom_branco_simpsons")
        self.tamanho_moletom_branco_simpsons.addItem("")
        self.tamanho_moletom_branco_simpsons.addItem("")
        self.tamanho_moletom_branco_simpsons.addItem("")
        self.tamanho_moletom_preto_naruto = QtWidgets.QComboBox(Dialog)
        self.tamanho_moletom_preto_naruto.setGeometry(QtCore.QRect(210, 520, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_moletom_preto_naruto.setFont(font)
        self.tamanho_moletom_preto_naruto.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_moletom_preto_naruto.setObjectName("tamanho_moletom_preto_naruto")
        self.tamanho_moletom_preto_naruto.addItem("")
        self.tamanho_moletom_preto_naruto.addItem("")
        self.tamanho_moletom_preto_naruto.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p>MOLETOM NARUTO - BRANCO</p><p><span style=\" font-weight:600;\">R$ 90,00</span></p><p><br/></p></body></html>"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>MOLETOM SIMPSONS - PRETO</p><p><span style=\" font-weight:600;\">R$ 90,00</span></p><p><br/></p></body></html>"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p>MOLETOM SIMPSONS - BRANCO</p><p><span style=\" font-weight:600;\">R$ 90,00</span></p><p><br/><br/></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p>MOLETOM NARUTO - PRETO</p><p><span style=\" font-weight:600;\">R$ 90,00</span></p><p><br/></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p>MOLETOM ONE PIECE - BRANCO</p><p><span style=\" font-weight:600;\">R$ 90,00</span></p><p><br/></p></body></html>"))
        self.botao_add_moletom_preto_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_moletom_branco_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">MOLETONS</span></p><p><br/></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_moletom_preto_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_moletom_branco_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p>MOLETOM ONE PIECE - PRETO</p><p><span style=\" font-weight:600;\">R$ 90,00</span></p><p><br/></p></body></html>"))
        self.botao_add_moletom_preto_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_add_moletom_branco_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_voltar.setText(_translate("Dialog", "VOLTAR"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.tamanho_moletom_preto_simpsons.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_moletom_preto_simpsons.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_moletom_preto_simpsons.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_moletom_branco_onepiece.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_moletom_branco_onepiece.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_moletom_branco_onepiece.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_moletom_branco_naruto.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_moletom_branco_naruto.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_moletom_branco_naruto.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_moletom_preto_onepiece.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_moletom_preto_onepiece.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_moletom_preto_onepiece.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_moletom_branco_simpsons.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_moletom_branco_simpsons.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_moletom_branco_simpsons.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_moletom_preto_naruto.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_moletom_preto_naruto.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_moletom_preto_naruto.setItemText(2, _translate("Dialog", "G"))
import template.imgicons
import template.produtos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Moletons()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
