# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shorts.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Shorts(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 670)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(70, 210, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.botao_add_short_rosa_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_short_rosa_onep.setGeometry(QtCore.QRect(310, 540, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_short_rosa_onep.setFont(font)
        self.botao_add_short_rosa_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_short_rosa_onep.setObjectName("botao_add_short_rosa_onep")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(550, 340, 151, 141))
        self.label_23.setStyleSheet("image: url(:/produtos/shorts/short-template-rosa-simpsons.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_23.setObjectName("label_23")
        self.botao_carrinho = QtWidgets.QPushButton(Dialog)
        self.botao_carrinho.setGeometry(QtCore.QRect(730, 10, 51, 51))
        self.botao_carrinho.setStyleSheet("image: url(:/icons/icones/carr.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:black;")
        self.botao_carrinho.setText("")
        self.botao_carrinho.setObjectName("botao_carrinho")
        self.botao_add_short_preto_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_short_preto_naruto.setGeometry(QtCore.QRect(70, 260, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_short_preto_naruto.setFont(font)
        self.botao_add_short_preto_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_short_preto_naruto.setObjectName("botao_add_short_preto_naruto")
        self.botao_add_short_rosa_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_short_rosa_simpsons.setGeometry(QtCore.QRect(550, 540, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_short_rosa_simpsons.setFont(font)
        self.botao_add_short_rosa_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_short_rosa_simpsons.setObjectName("botao_add_short_rosa_simpsons")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(360, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(320, 60, 161, 141))
        self.label_18.setStyleSheet("image: url(:/produtos/shorts/short-template-preto-onep-remove.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_18.setObjectName("label_18")
        self.botao_add_short_preto_onep = QtWidgets.QPushButton(Dialog)
        self.botao_add_short_preto_onep.setGeometry(QtCore.QRect(310, 260, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_short_preto_onep.setFont(font)
        self.botao_add_short_preto_onep.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_short_preto_onep.setObjectName("botao_add_short_preto_onep")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(70, 340, 181, 141))
        self.label_27.setStyleSheet("image: url(:/produtos/shorts/short-template-rosa-naruto.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_27.setObjectName("label_27")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(550, 60, 151, 141))
        self.label_21.setStyleSheet("image: url(:/produtos/shorts/short-template-preto-simpsons.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_21.setObjectName("label_21")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(320, 340, 161, 141))
        self.label_26.setStyleSheet("image: url(:/produtos/shorts/short-template-rosa-onep.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_26.setObjectName("label_26")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(320, 210, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(550, 210, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.label_6.setStyleSheet("image: url(:/icons/icones/Gamepad(1).png);\n"
"image: url(:/icons/icones/Gamepad (3).png);")
        self.label_6.setObjectName("label_6")
        self.botao_add_short_preto_simpsons = QtWidgets.QPushButton(Dialog)
        self.botao_add_short_preto_simpsons.setGeometry(QtCore.QRect(550, 260, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_short_preto_simpsons.setFont(font)
        self.botao_add_short_preto_simpsons.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_short_preto_simpsons.setObjectName("botao_add_short_preto_simpsons")
        self.botao_voltar = QtWidgets.QPushButton(Dialog)
        self.botao_voltar.setGeometry(QtCore.QRect(10, 630, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_voltar.setObjectName("botao_voltar")
        self.botao_add_short_rosa_naruto = QtWidgets.QPushButton(Dialog)
        self.botao_add_short_rosa_naruto.setGeometry(QtCore.QRect(70, 540, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_add_short_rosa_naruto.setFont(font)
        self.botao_add_short_rosa_naruto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_add_short_rosa_naruto.setObjectName("botao_add_short_rosa_naruto")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(70, 60, 181, 141))
        self.label_16.setStyleSheet("image: url(:/produtos/shorts/short-template-preto-naruto.png);\n"
"background-color: rgb(243, 243, 243);")
        self.label_16.setObjectName("label_16")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(320, 490, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(70, 490, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(550, 490, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.tamanho_short_preto_naruto = QtWidgets.QComboBox(Dialog)
        self.tamanho_short_preto_naruto.setGeometry(QtCore.QRect(190, 230, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_short_preto_naruto.setFont(font)
        self.tamanho_short_preto_naruto.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_short_preto_naruto.setObjectName("tamanho_short_preto_naruto")
        self.tamanho_short_preto_naruto.addItem("")
        self.tamanho_short_preto_naruto.addItem("")
        self.tamanho_short_preto_naruto.addItem("")
        self.tamanho_short_preto_onepiece = QtWidgets.QComboBox(Dialog)
        self.tamanho_short_preto_onepiece.setGeometry(QtCore.QRect(450, 230, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_short_preto_onepiece.setFont(font)
        self.tamanho_short_preto_onepiece.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_short_preto_onepiece.setObjectName("tamanho_short_preto_onepiece")
        self.tamanho_short_preto_onepiece.addItem("")
        self.tamanho_short_preto_onepiece.addItem("")
        self.tamanho_short_preto_onepiece.addItem("")
        self.tamanho_short_preto_simpsons = QtWidgets.QComboBox(Dialog)
        self.tamanho_short_preto_simpsons.setGeometry(QtCore.QRect(680, 230, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_short_preto_simpsons.setFont(font)
        self.tamanho_short_preto_simpsons.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_short_preto_simpsons.setObjectName("tamanho_short_preto_simpsons")
        self.tamanho_short_preto_simpsons.addItem("")
        self.tamanho_short_preto_simpsons.addItem("")
        self.tamanho_short_preto_simpsons.addItem("")
        self.tamanho_short_rosa_naruto = QtWidgets.QComboBox(Dialog)
        self.tamanho_short_rosa_naruto.setGeometry(QtCore.QRect(210, 510, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_short_rosa_naruto.setFont(font)
        self.tamanho_short_rosa_naruto.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_short_rosa_naruto.setObjectName("tamanho_short_rosa_naruto")
        self.tamanho_short_rosa_naruto.addItem("")
        self.tamanho_short_rosa_naruto.addItem("")
        self.tamanho_short_rosa_naruto.addItem("")
        self.tamanho_short_rosa_onepiece = QtWidgets.QComboBox(Dialog)
        self.tamanho_short_rosa_onepiece.setGeometry(QtCore.QRect(460, 510, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_short_rosa_onepiece.setFont(font)
        self.tamanho_short_rosa_onepiece.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_short_rosa_onepiece.setObjectName("tamanho_short_rosa_onepiece")
        self.tamanho_short_rosa_onepiece.addItem("")
        self.tamanho_short_rosa_onepiece.addItem("")
        self.tamanho_short_rosa_onepiece.addItem("")
        self.tamanho_short_rosa_simpsons = QtWidgets.QComboBox(Dialog)
        self.tamanho_short_rosa_simpsons.setGeometry(QtCore.QRect(680, 510, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tamanho_short_rosa_simpsons.setFont(font)
        self.tamanho_short_rosa_simpsons.setStyleSheet("border-color: rgb(173, 173, 173);\n"
"border-bottom-color: rgb(173, 173, 173);")
        self.tamanho_short_rosa_simpsons.setObjectName("tamanho_short_rosa_simpsons")
        self.tamanho_short_rosa_simpsons.addItem("")
        self.tamanho_short_rosa_simpsons.addItem("")
        self.tamanho_short_rosa_simpsons.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p>SHORT NARUTO - PRETO</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.botao_add_short_rosa_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_short_preto_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_add_short_rosa_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">SHORTS</span></p><p><br/></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.botao_add_short_preto_onep.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p>SHORT ONE PIECE - PRETO</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p>SHORT SIMPSONS - PRETO</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.botao_add_short_preto_simpsons.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.botao_voltar.setText(_translate("Dialog", "VOLTAR"))
        self.botao_add_short_rosa_naruto.setText(_translate("Dialog", "ADICIONAR AO CARRINHO"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p>SHORT ONE PIECE - ROSA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p>SHORT NARUTO - ROSA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>SHORT SIMPSONS - ROSA</p><p><span style=\" font-weight:600;\">R$ 70,00</span></p><p><br/></p></body></html>"))
        self.tamanho_short_preto_naruto.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_short_preto_naruto.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_short_preto_naruto.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_short_preto_onepiece.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_short_preto_onepiece.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_short_preto_onepiece.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_short_preto_simpsons.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_short_preto_simpsons.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_short_preto_simpsons.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_short_rosa_naruto.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_short_rosa_naruto.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_short_rosa_naruto.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_short_rosa_onepiece.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_short_rosa_onepiece.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_short_rosa_onepiece.setItemText(2, _translate("Dialog", "G"))
        self.tamanho_short_rosa_simpsons.setItemText(0, _translate("Dialog", "P"))
        self.tamanho_short_rosa_simpsons.setItemText(1, _translate("Dialog", "M"))
        self.tamanho_short_rosa_simpsons.setItemText(2, _translate("Dialog", "G"))
import template.imgicons
import template.produtos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Shorts()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
